var DATA = {
  stats: [
    { id: "int", name: "INT", full: "Intelligence", desc: "Memory, deduction, pattern recognition" },
    { id: "ref", name: "REF", full: "Reflexes", desc: "Reaction time, coordination" },
    { id: "dex", name: "DEX", full: "Dexterity", desc: "Fine motor control, steady hands" },
    { id: "tech", name: "TECH", full: "Technical Ability", desc: "Repair, crafting, operating devices" },
    { id: "cool", name: "COOL", full: "Composure", desc: "Nerves under pressure, charisma" },
    { id: "will", name: "WILL", full: "Willpower", desc: "Mental fortitude, resistance" },
    { id: "luck", name: "LUCK", full: "Luck", desc: "Fortune, fate. Spend to reroll or add to a roll" },
    { id: "move", name: "MOVE", full: "Movement", desc: "Speed, agility, distance covered" },
    { id: "body", name: "BODY", full: "Body", desc: "Strength, toughness, endurance" },
    { id: "emp", name: "EMP", full: "Empathy", desc: "Humanity, social awareness" }
  ],

  roles: [
    { id: "solo", name: "Solo", ability: "Combat Awareness", desc: "Masters of combat. Add REF to initiative. Use Combat Awareness points each turn to boost attacks (+1 to hit), defense (+1 to dodge/block), or damage (+1 to damage).",
      rankDesc: [
        "",
        "1 Combat Awareness point per turn. Can distribute 1 point among +1 Attack, +1 Defense, or +1 Damage.",
        "2 points per turn. May split between Attack, Defense, and Damage.",
        "3 points per turn.",
        "4 points per turn. Gain the ability to Spot敌人的弱点 as a Free Action once per turn.",
        "5 points per turn.",
        "6 points per turn. Gain Foresight — go first in combat regardless of initiative once per session.",
        "7 points per turn.",
        "8 points per turn. Gain Always Watching — cannot be surprised and ignore ambush penalties.",
        "9 points per turn.",
        "10 points per turn. Gain One-Man Army — once per combat, take an additional full round of actions."
      ] },
    { id: "rockerboy", name: "Rockerboy", ability: "Charismatic Impact", desc: "Megastars who move the masses. Use Charismatic Impact to spread messages through society using Perform (or similar) checks.",
      rankDesc: [
        "",
        "Affects 1 person. Can deliver a simple message. DV9 to sway them.",
        "Affects up to 2 people. DV9 to sway a small group.",
        "Affects up to 4 people. DV13 to sway a small crowd.",
        "Affects up to 8 people. DV13 to sway a moderate crowd. Message can spread by word of mouth over 1d6 days.",
        "Affects up to 15 people. DV15 to sway a large crowd.",
        "Affects up to 30 people. DV15 to sway a very large crowd. Message spreads across a district in 1d6 days.",
        "Affects up to 60 people. DV17 to sway a massive crowd.",
        "Affects up to 120 people. DV17. Message spreads across a city in 1d6/2 days.",
        "Affects up to 250 people. DV19. Message spreads across a region in 1d6/3 days.",
        "Affects up to 500+ people. DV19. Message spreads across the entire city in 1d6 hours. Gain a loyal following."
      ] },
    { id: "netrunner", name: "Netrunner", ability: "Interface", desc: "Cyberspace hackers who breach NET architectures and control programs. Interface Rank determines the maximum NET Architecture floor you can reach.",
      rankDesc: [
        "",
        "Interface Rank 1. Can enter NET architectures up to 1 floor deep. +1 Program slot. Can control 1 program at a time.",
        "Interface Rank 2. Can enter up to 2 floors deep. +1 Program slot. May control up to 2 programs.",
        "Interface Rank 3. Up to 3 floors. +1 Program slot. Control up to 3 programs.",
        "Interface Rank 4. Up to 4 floors. +1 Program slot. Control up to 4 programs. Gain +1 to all NET actions.",
        "Interface Rank 5. Up to 5 floors. +1 Program slot. Control up to 5 programs.",
        "Interface Rank 6. Up to 6 floors. +1 Program slot. Control up to 6 programs. Gain +2 to all NET actions.",
        "Interface Rank 7. Up to 7 floors. +1 Program slot. Control up to 7 programs.",
        "Interface Rank 8. Up to 8 floors. +1 Program slot. Control up to 8 programs. Gain +3 to all NET actions.",
        "Interface Rank 9. Up to 9 floors. +1 Program slot. Control up to 9 programs.",
        "Interface Rank 10. Up to 10 floors. +1 Program slot. Control up to 10 programs. Gain +4 to all NET actions."
      ] },
    { id: "tech", name: "Tech", ability: "Maker", desc: "Inventors and repairers. Fabricate items using Invention Slots and upgrade gear with Fabrication Checks.",
      rankDesc: [
        "",
        "1 Invention Slot. Can fabricate DV9 items. Can Field Strip a single device as an Action.",
        "1 Invention Slot. Can upgrade weapons/armor by 1 level (DV13).",
        "2 Invention Slots. Can fabricate DV13 items. Field Strip as a Free Action once per turn.",
        "2 Invention Slots. Can upgrade weapons/armor by 2 levels (DV15).",
        "3 Invention Slots. Can fabricate DV15 items. Can upgrade cyberware (DV15).",
        "3 Invention Slots. Can upgrade weapons/armor by 3 levels (DV17). Field Strip any device instantly.",
        "4 Invention Slots. Can fabricate DV17 items. Can upgrade cyberware by 2 levels (DV17).",
        "4 Invention Slots. Can upgrade weapons/armor by 4 levels (DV19). Can invent entirely new items (Referee approval).",
        "5 Invention Slots. Can fabricate DV19 items. Upgrades cost half time and materials.",
        "5 Invention Slots. Master Maker. Can upgrade anything by any level (DV19). Fabrication takes half time."
      ] },
    { id: "medtech", name: "Medtech", ability: "Medicine", desc: "Trauma surgeons and cyber-docs. Perform surgery, treat critical injuries, and install/remove cyberware using their Medicine skill.",
      rankDesc: [
        "",
        "Crisis/Surgery Rank 1. Can treat 1 Critical Injury per operation. Can install Standard cyberware (DV9). Can diagnose injuries as an Action.",
        "Crisis/Surgery Rank 2. Can treat up to 2 Critical Injuries per operation.",
        "Crisis/Surgery Rank 3. Can install Premium cyberware (DV13). Can perform emergency field surgery.",
        "Crisis/Surgery Rank 4. Can treat up to 3 Critical Injuries per operation. Stabilize a dying patient as a Single Action.",
        "Crisis/Surgery Rank 5. Can install Excellent cyberware (DV15). Surgery recovery time halved.",
        "Crisis/Surgery Rank 6. Can treat up to 4 Critical Injuries per operation. Can install cyberware in half the normal time.",
        "Crisis/Surgery Rank 7. Can install Borg cyberware (DV17). Can perform surgery without a clinic (field conditions).",
        "Crisis/Surgery Rank 8. Can treat any number of Critical Injuries per operation. Surgery recovery time reduced to 1/3.",
        "Crisis/Surgery Rank 9. Can install any cyberware including prototype/Beta (DV19).",
        "Crisis/Surgery Rank 10. Master Medtech. Surgery takes 1/4 normal time. Can revive a clinically dead patient within 1 minute (Referee discretion)."
      ] },
    { id: "exec", name: "Exec", ability: "Team", desc: "Corporate officers with access to resources and a team of loyal subordinates. Team members scale with rank.",
      rankDesc: [
        "",
        "1 team member (Rank 1 — intern/assistant). Access to a modest corporate apartment. Small expense account (500eb/month).",
        "2 team members (Ranks 1-2). Slightly better apartment. Expense account of 1,000eb/month.",
        "2 team members (Ranks 1-3). Mid-range corporate housing. 2,000eb/month expense account. Access to corporate gym.",
        "3 team members (Ranks 1-4). 1 team member can be Rank 4. 4,000eb/month. Corporate vehicle (Economy).",
        "3 team members (Ranks 1-5). 1 team member can be Rank 5. 8,000eb/month expense account. Corporate vehicle (Mid-Range).",
        "4 team members (Ranks 1-6). 1 team member can be Rank 6. 12,000eb/month. Executive suite. Corporate vehicle (Luxury).",
        "5 team members (Ranks 1-7). 1 team member can be Rank 7. 20,000eb/month. Floor of corporate tower. AV-4 access.",
        "5 team members (Ranks 1-8). 1 team member can be Rank 8. 30,000eb/month. Corporate jet for inter-city travel.",
        "6 team members (Ranks 1-9). 1 team member can be Rank 9. 50,000eb/month. Full executive floor. Company helicopter.",
        "6 team members (Ranks 1-10). 1 team member can be Rank 10. 100,000eb/month. Near-total corporate resource access (subject to Referee)."
      ] },
    { id: "lawman", name: "Lawman", ability: "Backup", desc: "Badges who call in backup. The higher the rank, the faster and more powerful the response.",
      rankDesc: [
        "",
        "Call Backup (arrives in 1d10/2 rounds). 1 officer arrives (armed with Heavy Pistol, Light Armorjack).",
        "Call Backup (1d10/2 rounds). 2 officers arrive.",
        "Call Backup (1d10/2 rounds). 3 officers. One has a Shotgun.",
        "Call Backup (1d10/2 rounds). 4 officers. Squad has one AV-4 for transport.",
        "Call Backup (1d10 rounds). 2 officers + 1 AV-4 gunship with door gunner. Officers carry Assault Rifles.",
        "Call Backup (1d10 rounds). 3 officers + 1 AV-4. One officer carries a Sniper Rifle.",
        "Call Backup (1d10 rounds). 4 officers + 1 AV-4 + Air Support (attack helicopter). Can declare a Code Red — all officers in district respond.",
        "Call Backup (1d6 rounds). MaxTac team arrives (4 operatives with heavy weapons and full borg conversion).",
        "Call Backup (1d6 rounds). MaxTac team + AV-4 gunship. Can declare a Code Black — MaxTac and all available LEOs respond.",
        "Call Backup (1d6 rounds). Full MaxTac strike force (6 operatives, 2 AV-4s, Air Support). Once per session, call in an airstrike or orbital strike (Referee discretion)."
      ] },
    { id: "fixer", name: "Fixer", ability: "Operator", desc: "Dealers who find anything for a price. Gain Contacts and street price reduction on purchased items.",
      rankDesc: [
        "",
        "1 Contact. Gain a 100eb x Rank discount on purchased items (max 50% off). Can find any item up to Premium availability.",
        "2 Contacts. 200eb x Rank discount. Can find any item up to Premium availability.",
        "3 Contacts. 300eb x Rank discount. Can find items up to Excellent availability.",
        "4 Contacts. 400eb x Rank discount. Can find items up to Excellent availability.",
        "5 Contacts. 500eb x Rank discount. Can find items up to Luxury availability. Can fence stolen goods for 50% value.",
        "6 Contacts. 600eb x Rank discount. Can find items up to Luxury availability. Fence for 60% value.",
        "7 Contacts. 700eb x Rank discount. Can find any item (including military/restricted). Fence for 70% value.",
        "8 Contacts. 800eb x Rank discount. Can find any item. One contact is a Fixer — can source jobs. Fence for 80%.",
        "9 Contacts. 900eb x Rank discount. Can find multiple units of restricted items. Fence for 90%.",
        "10 Contacts. 1000eb x Rank discount (max 50% off). Can find anything within 1d6 days. Fence for 100%. Gain a private Night Market."
      ] },
    { id: "nomad", name: "Nomad", ability: "Moto", desc: "Transport experts who call in vehicles and modify them. Gains vehicles, upgrade slots, and the ability to drive anything.",
      rankDesc: [
        "",
        "1 vehicle (Economy — car or bike). +1 upgrade slot. Can hotwire any ground vehicle in 1d10 rounds.",
        "1 vehicle (Economy). +2 upgrade slots. Can drive any ground vehicle without penalty.",
        "1 vehicle (Mid-Range quality). +3 upgrade slots. Can pilot any air vehicle without penalty.",
        "1 vehicle (Mid-Range). +4 upgrade slots. Once per session, call in a favor for a temporary vehicle.",
        "1 vehicle (Luxury or Performance quality). +5 upgrade slots. Can pilot any vehicle without penalty (including watercraft).",
        "2 vehicles (1 Luxury/Performance, 1 Mid-Range). +6 upgrade slots. Vehicles can be called in within 1d10 minutes.",
        "2 vehicles (1 Super/Luxury, 1 Mid-Range). +7 upgrade slots. Can modify vehicles to add hidden weapon mounts.",
        "2 vehicles (1 Super/Luxury, 1 Economy). +8 upgrade slots. One vehicle can be a Heavy (armored truck/tank).",
        "3 vehicles (varying quality). +9 upgrade slots. Vehicles can be called in within 1d10/2 minutes. Can have a home base (garage/compound).",
        "3 vehicles (1 Supercar/Luxury custom). +10 upgrade slots. Can call in a favor for any vehicle (including military/experimental). Gain a mobile command vehicle."
      ] },
    { id: "media", name: "Media", ability: "Credibility", desc: "Investigative reporters who dig up the truth. Credibility determines sources per story and questions per source.",
      rankDesc: [
        "",
        "1 source per story. 1 question per source. Can identify public information with a DV9 Library Search check.",
        "1 source per story. 2 questions per source. Sources are more willing to talk (DV9 Human Perception to detect lies).",
        "2 sources per story. 2 questions per source. Can access city records with a DV13 check.",
        "2 sources per story. 3 questions per source. Sources will share documents/proof (DV13).",
        "3 sources per story. 3 questions per source. Can access corporate records with a DV15 check.",
        "3 sources per story. 4 questions per source. Gain a Deep Source — a high-level informant (Referee-assigned).",
        "4 sources per story. 4 questions per source. Can access military/government records (DV17). Stories reach a city-wide audience.",
        "4 sources per story. 5 questions per source. Deep Source becomes a reliable contact. Stories can start investigations by authorities (DV17 resist).",
        "5 sources per story. 5 questions per source. Can access any records with a DV19 check. Stories spread region-wide in 1d6 days.",
        "5 sources per story. Unlimited questions. Gain an Anonymous Source Network — once per session, get a piece of critical information from an unknown source. Stories can topple corporations (subject to play)."
      ] }
  ],

  skills: {
    int: [
      { id: "accounting", name: "Accounting" },
      { id: "animal_handling", name: "Animal Handling" },
      { id: "bureaucracy", name: "Bureaucracy" },
      { id: "business", name: "Business" },
      { id: "composition", name: "Composition" },
      { id: "criminology", name: "Criminology" },
      { id: "cryptography", name: "Cryptography" },
      { id: "deduction", name: "Deduction" },
      { id: "education", name: "Education" },
      { id: "gambling", name: "Gambling" },
      { id: "history", name: "History" },
      { id: "human_perception", name: "Human Perception" },
      { id: "language", name: "Language" },
      { id: "library_search", name: "Library Search" },
      { id: "local_expert", name: "Local Expert" },
      { id: "navigation", name: "Navigation" },
      { id: "networking", name: "Networking" },
      { id: "photography", name: "Photography" },
      { id: "programming", name: "Programming" },
      { id: "psychology", name: "Psychology" },
      { id: "science", name: "Science" },
      { id: "search_and_spot", name: "Search & Spot" },
      { id: "surveillance", name: "Surveillance" },
      { id: "survival", name: "Survival" },
      { id: "tactics", name: "Tactics" },
      { id: "tracking", name: "Tracking" },
      { id: "wilderness_survival", name: "Wilderness Survival" }
    ],
    ref: [
      { id: "airlift", name: "Airlift" },
      { id: "archery", name: "Archery" },
      { id: "autofire", name: "Autofire" },
      { id: "drive_land", name: "Drive Land Vehicle" },
      { id: "handgun", name: "Handgun" },
      { id: "heavy_weapons", name: "Heavy Weapons" },
      { id: "melee_weapon", name: "Melee Weapon" },
      { id: "motorcycle", name: "Motorcycle" },
      { id: "operate_heavy", name: "Operate Heavy Machinery" },
      { id: "pilot_air", name: "Pilot Air" },
      { id: "pilot_sea", name: "Pilot Sea" },
      { id: "riding", name: "Riding" },
      { id: "shoulder_arms", name: "Shoulder Arms" },
      { id: "stealth", name: "Stealth" }
    ],
    dex: [
      { id: "athletics", name: "Athletics" },
      { id: "brawling", name: "Brawling" },
      { id: "dance", name: "Dance" },
      { id: "evasion", name: "Evasion" },
      { id: "martial_arts", name: "Martial Arts" },
      { id: "parry", name: "Parry" },
      { id: "swimming", name: "Swimming" }
    ],
    tech: [
      { id: "basic_tech", name: "Basic Tech" },
      { id: "chemistry", name: "Chemistry" },
      { id: "cybertech", name: "Cybertech" },
      { id: "demolitions", name: "Demolitions" },
      { id: "disguise", name: "Disguise" },
      { id: "electronics", name: "Electronics/Security Tech" },
      { id: "first_aid", name: "First Aid" },
      { id: "forgery", name: "Forgery" },
      { id: "invent", name: "Invent" },
      { id: "paramedic", name: "Paramedic" },
      { id: "photography_tech", name: "Photography" },
      { id: "pick_lock", name: "Pick Lock" },
      { id: "pick_pocket", name: "Pick Pocket" },
      { id: "play_instrument", name: "Play Instrument" },
      { id: "weaponsmith", name: "Weaponsmith" }
    ],
    cool: [
      { id: "acting", name: "Acting" },
      { id: "bribery", name: "Bribery" },
      { id: "conceal_reveal", name: "Conceal/Reveal Object" },
      { id: "conversation", name: "Conversation" },
      { id: "interrogation", name: "Interrogation" },
      { id: "perform", name: "Perform" },
      { id: "persuasion", name: "Persuasion" },
      { id: "streetwise", name: "Streetwise" },
      { id: "trading", name: "Trading" },
      { id: "wardrobe_and_style", name: "Wardrobe & Style" }
    ],
    will: [
      { id: "concentration", name: "Concentration" },
      { id: "resist_torture", name: "Resist Torture/Drugs" }
    ],
    body: [
      { id: "endurance", name: "Endurance" },
      { id: "resist_disease", name: "Resist Disease/Poison" }
    ],
    emp: [
      { id: "empathy", name: "Empathy" },
      { id: "social", name: "Social" }
    ]
  },

  weapons: [
    { id: "heavy_pistol", name: "Heavy Pistol", type: "Handgun", dmg: "3d6", hands: 1, rof: 2, mag: 12, conceal: "Jacket", cost: 500, desc: "Standard heavy pistol" },
    { id: "light_pistol", name: "Light Pistol", type: "Handgun", dmg: "2d6", hands: 1, rof: 2, mag: 15, conceal: "Pocket", cost: 250, desc: "Small concealable pistol" },
    { id: "very_heavy_pistol", name: "Very Heavy Pistol", type: "Handgun", dmg: "4d6", hands: 1, rof: 1, mag: 8, conceal: "Jacket", cost: 750, desc: "Large caliber pistol" },
    { id: "assault_rifle", name: "Assault Rifle", type: "Shoulder Arms", dmg: "5d6", hands: 2, rof: 1, mag: 25, conceal: "Long gun", cost: 1000, desc: "Full-auto capable rifle" },
    { id: "smg", name: "Submachine Gun", type: "Shoulder Arms", dmg: "3d6", hands: 2, rof: 2, mag: 30, conceal: "Long gun", cost: 750, desc: "Automatic weapon" },
    { id: "shotgun_pump", name: "Shotgun (Pump)", type: "Shoulder Arms", dmg: "5d6", hands: 2, rof: 1, mag: 6, conceal: "Long gun", cost: 500, desc: "Pump-action shotgun" },
    { id: "shotgun_auto", name: "Shotgun (Auto)", type: "Shoulder Arms", dmg: "5d6", hands: 2, rof: 2, mag: 10, conceal: "Long gun", cost: 1000, desc: "Automatic shotgun" },
    { id: "sniper_rifle", name: "Sniper Rifle", type: "Shoulder Arms", dmg: "5d6", hands: 2, rof: 1, mag: 6, conceal: "Cannot conceal", cost: 1500, desc: "Long range precision rifle" },
    { id: "heavy_smg", name: "Heavy SMG", type: "Shoulder Arms", dmg: "4d6", hands: 2, rof: 2, mag: 40, conceal: "Long gun", cost: 1000, desc: "Large caliber SMG" },
    { id: "heavy_pistol_smart", name: "Smart Heavy Pistol", type: "Handgun", dmg: "3d6", hands: 1, rof: 2, mag: 12, conceal: "Jacket", cost: 2000, desc: "Smart-linked heavy pistol" },
    { id: "medium_pistol", name: "Medium Pistol", type: "Handgun", dmg: "2d6+3", hands: 1, rof: 2, mag: 14, conceal: "Jacket", cost: 350, desc: "Reliable medium pistol" },
    { id: "bow", name: "Bow", type: "Archery", dmg: "4d6", hands: 2, rof: 1, mag: 1, conceal: "Long gun", cost: 200, desc: "Compound hunting bow" },
    { id: "crossbow", name: "Crossbow", type: "Archery", dmg: "4d6", hands: 2, rof: 1, mag: 1, conceal: "Long gun", cost: 300, desc: "Silent ranged weapon" },
    { id: "grenade_frag", name: "Frag Grenade", type: "Heavy Weapons", dmg: "6d6", hands: 1, rof: 1, mag: null, conceal: "Pocket", cost: 100, desc: "High explosive fragmentation grenade" },
    { id: "grenade_smoke", name: "Smoke Grenade", type: "Heavy Weapons", dmg: "0", hands: 1, rof: 1, mag: null, conceal: "Pocket", cost: 50, desc: "Creates smoke screen" },
    { id: "knife", name: "Knife", type: "Melee Weapon", dmg: "1d6", hands: 1, conceal: "Pocket", cost: 50, desc: "Standard combat knife" },
    { id: "machete", name: "Machete", type: "Melee Weapon", dmg: "2d6", hands: 1, conceal: "Jacket", cost: 100, desc: "Heavy blade" },
    { id: "katana", name: "Katana", type: "Melee Weapon", dmg: "3d6", hands: 2, conceal: "Long gun", cost: 500, desc: "Masterwork blade" },
    { id: "lead_pipe", name: "Lead Pipe", type: "Melee Weapon", dmg: "2d6", hands: 1, conceal: "Jacket", cost: 10, desc: "Heavy metal pipe" },
    { id: "baseball_bat", name: "Baseball Bat", type: "Melee Weapon", dmg: "2d6", hands: 2, conceal: "Long gun", cost: 20, desc: "Standard baseball bat" },
    { id: "tonfa", name: "Tonfa", type: "Melee Weapon", dmg: "2d6", hands: 1, conceal: "Jacket", cost: 50, desc: "Police-issue tonfa" },
    { id: "chainsaw", name: "Chainsaw", type: "Melee Weapon", dmg: "4d6", hands: 2, conceal: "Cannot conceal", cost: 200, desc: "Powered saw blade" },
    { id: "stun_baton", name: "Stun Baton", type: "Melee Weapon", dmg: "1d6+stun", hands: 1, conceal: "Jacket", cost: 150, desc: "Electric stun baton" },
    { id: "big_dreem", name: "Big Dreem", type: "Autofire", dmg: "3d6", hands: 1, rof: 1, mag: 30, conceal: "No", cost: 10, desc: "Exotic SMG, Autofire only. Continues firing for 2 turns after trigger pulled." },
    { id: "everest_sportmaster", name: "Everest SportMaster", type: "Shoulder Arms", dmg: "3d6", hands: 2, rof: 1, mag: 25, conceal: "No", cost: 50, desc: "Assault Rifle, single shot only. Only loads Small Game Ammo." },
    { id: "everest_survivalmaster", name: "Everest SurvivalMaster", type: "Shoulder Arms", dmg: "5d6", hands: 2, rof: 1, mag: 5, conceal: "Yes (disassembled)", cost: 100, desc: "Exotic Assault Rifle. Can disassemble to fit in stock for concealment." },
    { id: "sanroo_hello_cutie", name: "Sanroo Hello Cutie 1TruLuv", type: "Shoulder Arms", dmg: "5d6", hands: 2, rof: 1, mag: 4, conceal: "No", cost: 1000, desc: "Exotic Sniper Rifle with Sniper Scope, Nightvision Scope, and pseudo AI girlfriend." },
    { id: "molotov_cocktail", name: "Molotov Cocktail", type: "Athletics", dmg: "5d6", hands: 1, rof: 1, mag: null, conceal: "No", cost: 20, desc: "Incendiary grenade. 50% chance to break when you take damage, setting you on fire." },
    { id: "timeless_ww1_conversion", name: "Timeless WW1 Conversion", type: "Handgun", dmg: "4d6", hands: 1, rof: 1, mag: 5, conceal: "No", cost: 20, desc: "Poor Quality VH Pistol. Requires an Action to chamber next round." }
  ],

  armor: [
    { id: "armor_head_light", name: "Light Armorjack (Head)", slots: "Head", sp: 7, cost: 50, enc: 2 },
    { id: "armor_head_medium", name: "Medium Armorjack (Head)", slots: "Head", sp: 11, cost: 100, enc: 4 },
    { id: "armor_head_heavy", name: "Heavy Armorjack (Head)", slots: "Head", sp: 15, cost: 200, enc: 6 },
    { id: "armor_body_light", name: "Light Armorjack (Body)", slots: "Body", sp: 7, cost: 100, enc: 4 },
    { id: "armor_body_medium", name: "Medium Armorjack (Body)", slots: "Body", sp: 11, cost: 200, enc: 8 },
    { id: "armor_body_heavy", name: "Heavy Armorjack (Body)", slots: "Body", sp: 15, cost: 400, enc: 12 },
    { id: "armor_body_flak", name: "Flak (Body)", slots: "Body", sp: 18, cost: 1000, enc: 16 },
    { id: "armor_body_metalgear", name: "Metal Gear (Body)", slots: "Body", sp: 20, cost: 5000, enc: 20 },
    { id: "kevlar_vest", name: "Kevlar Vest", slots: "Body", sp: 7, cost: 50, enc: 2 },
    { id: "leather_jacket", name: "Leather Jacket", slots: "Body", sp: 4, cost: 20, enc: 1 },
    { id: "shield_riot", name: "Riot Shield", slots: "Shield", sp: 7, cost: 100, enc: 4 },
    { id: "shield_ballistic", name: "Ballistic Shield", slots: "Shield", sp: 11, cost: 250, enc: 6 },
    { id: "scavenged_armor", name: "Scavenged Armor", slots: "Body", sp: 11, cost: 50, enc: 4 },
    { id: "dirk_combat_jacket", name: "Dirk Combat Jacket", slots: "Body", sp: 11, cost: 500, enc: 4 },
    { id: "laser_light_jacket", name: "Laser Light Street Jacket", slots: "Body", sp: 11, cost: 500, enc: 4 },
    { id: "montage_variable", name: "Montage Variable Clothing", slots: "Body", sp: 11, cost: 500, enc: 4 },
    { id: "corporate_island", name: "Corporate Island Armor", slots: "Body", sp: 11, cost: 500, enc: 4 },
    { id: "executive_armor", name: "Executive Armor", slots: "Body", sp: 11, cost: 1000, enc: 4 },
    { id: "mimic_clothing_kit", name: "Mimic Clothing Kit", slots: "Body", sp: 11, cost: 100, enc: 4 },
    { id: "masetto_airrider", name: "Masetto AirRider", slots: "Body", sp: 7, cost: 100, enc: 2 },
    { id: "shock_armor", name: "Shock Armor", slots: "Body", sp: 7, cost: 500, enc: 2 },
    { id: "skidrow_trench", name: "SkidRow Trench", slots: "Body", sp: 13, cost: 100, enc: 6 },
    { id: "fire_brand_bunker", name: "Fire Brand Bunker Gear", slots: "Body", sp: 15, cost: 1000, enc: 8 },
    { id: "lotos_netsuit", name: "Lotos Netsuit", slots: "Body", sp: 13, cost: 5000, enc: 6 },
    { id: "mechaman_helmet", name: "MechaMan Helmet", slots: "Head", sp: 15, cost: 5000, enc: 6 }
  ],

  cyberware: [
    { id: "cybereye", name: "Cybereye", type: "Fashion", hc: 2, cost: 500, desc: "Single cybernetic eye. Can hold options." },
    { id: "cybereye_options", name: "Cybereye Options", type: "Fashion", hc: 1, cost: 200, desc: "Per option slot (IR, low-light, video, etc.)" },
    { id: "cyberaudio", name: "Cyberaudio", type: "Fashion", hc: 2, cost: 500, desc: "Internal ear comms and audio processing." },
    { id: "cyberaudio_options", name: "Cyberaudio Options", type: "Fashion", hc: 1, cost: 200, desc: "Per option slot (radio, voice stress, etc.)" },
    { id: "neural_link", name: "Neural Link", type: "Internal", hc: 3, cost: 1000, desc: "Chip socket interface. Required for most internal cyberware." },
    { id: "chipware_socket", name: "Chipware Socket", type: "Internal", hc: 2, cost: 500, desc: "Extra skill chip socket." },
    { id: "pain_editor", name: "Pain Editor", type: "Internal", hc: 4, cost: 2000, desc: "Disables pain. +5 to Resist Torture/Drugs." },
    { id: "nanosurgeons", name: "Nanosurgeons", type: "Internal", hc: 3, cost: 1500, desc: "Auto-stabilize at 0 HP once per day." },
    { id: "synth_lungs", name: "Synth Lungs", type: "Internal", hc: 3, cost: 1000, desc: "Filter toxins, breathe smoke." },
    { id: "gills", name: "Gills", type: "Internal", hc: 2, cost: 500, desc: "Breathe underwater." },
    { id: "cyberarm", name: "Cyberarm", type: "Fashion", hc: 3, cost: 1000, desc: "Basic cybernetic arm." },
    { id: "cyberarm_options", name: "Cyberarm Options", type: "Fashion", hc: 1, cost: 500, desc: "Per option (popup weapon, hide-a-key, etc.)" },
    { id: "cyberleg", name: "Cyberleg", type: "Fashion", hc: 3, cost: 1000, desc: "Basic cybernetic leg." },
    { id: "cyberleg_options", name: "Cyberleg Options", type: "Fashion", hc: 1, cost: 500, desc: "Per option (hydraulic rams, skate feet, etc.)" },
    { id: "tactile_boost", name: "Tactile Boost", type: "Fashion", hc: 2, cost: 500, desc: "Enhanced touch, +1 to pick lock/pick pocket." },
    { id: "olfactory_boost", name: "Olfactory Boost", type: "Fashion", hc: 1, cost: 300, desc: "Enhanced smell, +2 to tracking via scent." },
    { id: "subdermal_armor", name: "Subdermal Armor", type: "Internal", hc: 4, cost: 2000, desc: "SP 7 to area implanted." },
    { id: "skin_weave", name: "Skin Weave", type: "Internal", hc: 3, cost: 1500, desc: "SP 4 all over." },
    { id: "pneumatics", name: "Pneumatics", type: "Internal", hc: 3, cost: 2000, desc: "+2 to BODY for melee damage." },
    { id: "hydraulic_rams", name: "Hydraulic Rams", type: "Fashion", hc: 3, cost: 1500, desc: "Cyberleg option, +2 MOVE when jumping." },
    { id: "big_knucks", name: "Big Knucks", type: "Fashion", hc: 1, cost: 100, desc: "Brass knuckles built into cyberarm." },
    { id: "popup_weapon", name: "Popup Weapon (Cyberarm)", type: "Fashion", hc: 2, cost: 500, desc: "Hidden weapon in cyberarm." },
    { id: "implanted_lavatory", name: "Implanted Lavatory", type: "Fashion", hc: 1, cost: 200, desc: "Waste processing implant." },
    { id: "light_tattoo", name: "Light Tattoo", type: "Fashion", hc: 0, cost: 200, desc: "LED subdermal tattoos." },
    { id: "agency_record", name: "Agency Record", type: "Fashion", hc: 1, cost: 500, desc: "Always-on recording of everything you see/hear." },
    { id: "buddy_link", name: "Buddy Link", type: "Fashion", hc: 1, cost: 200, desc: "Private short-range comm with your crew." },
    { id: "bc_budget_chipware", name: "Budget Chipware Socket", type: "Neuralware", hc: 7, cost: 100, desc: "A cheap chipware socket." },
    { id: "bc_discount_audio", name: "Discount Cyberaudio Suite", type: "Cyberaudio", hc: 3, cost: 100, desc: "An inferior audio suite at an affordable price." },
    { id: "bc_explicit_memory", name: "Explicit Memory Stimulator", type: "Chipware", hc: 3, cost: 100, desc: "+2 to Concentration Checks to remember information." },
    { id: "bc_extra_jointed", name: "Extra-Jointed Cyberlimb Upgrade", type: "Cyberlimb", hc: 3, cost: 500, desc: "Extra points of articulation for your limb." },
    { id: "bc_flashbulb", name: "Flashbulb", type: "Cyberarm", hc: 7, cost: 500, desc: "Blind your enemies with your arm." },
    { id: "bc_hardened_cybereye", name: "Hardened Cybereye Casing", type: "Cybereye", hc: 3, cost: 500, desc: "Protect your Cybereye against EMP effects." },
    { id: "bc_health_monitor", name: "Heuristic Health Monitor", type: "Fashionware", hc: 0, cost: 500, desc: "You're fit and now you can show the world." },
    { id: "bc_integrated_cyberdeck", name: "Integrated Cyberdeck Upgrade", type: "Cyberarm", hc: 7, cost: 500, desc: "An extra option slot for your arm-installed Cyberdeck." },
    { id: "bc_modular_finger_hand", name: "Modular Finger Cyberhand", type: "Cyberarm", hc: 3, cost: 100, desc: "A hand for modular Cyberfingers." },
    { id: "bc_neo_soviet_arm", name: "Neo-Soviet Cyberarm", type: "Cyberarm", hc: 7, cost: 100, desc: "Neo-Soviet charm for your Cyberarm." },
    { id: "bc_popup_net", name: "Popup Net Launcher", type: "Cyberarm", hc: 7, cost: 500, desc: "Shoot nets from your arm." },
    { id: "bc_popup_shotgun", name: "Popup Shotgun", type: "Cyberarm", hc: 7, cost: 1000, desc: "A shotgun in your arm." },
    { id: "bc_racerbracer", name: "RacerBracer", type: "Internal Body", hc: 7, cost: 500, desc: "Immunity to Whiplash Critical Injury." },
    { id: "bc_reflex_coprocessor", name: "Reflex Co-Processor", type: "Neuralware", hc: 14, cost: 500, desc: "Dodge bullets without REF 8." },
    { id: "bc_reinforced_limb", name: "Reinforced Cyberlimb Upgrade", type: "Cyberlimb", hc: 3, cost: 1000, desc: "Say goodbye to breaking this limb." },
    { id: "bc_sponsored_cybereye", name: "Sponsored Cybereye", type: "Cybereye", hc: 7, cost: 50, desc: "A cheap Cybereye with Chyron and pop-up ads." },
    { id: "bc_trauma_nanomatrix", name: "Trauma Response Nanomatrix", type: "Internal Body", hc: 7, cost: 1000, desc: "Restore all lost Skinweave or Subdermal Armor SP once/day." },
    { id: "bc_standard_cyberfinger", name: "Standard Cyberfinger", type: "Cyberfinger", hc: 0, cost: 20, desc: "A Cyberfinger with no special features. Requires Modular Finger Cyberhand." },
    { id: "bc_lockpick_cyberfinger", name: "Lockpick Cyberfinger", type: "Cyberfinger", hc: 2, cost: 100, desc: "Adjustable lockpick and tensioning tool. Requires Modular Finger Cyberhand." },
    { id: "bc_microphone_cyberfinger", name: "Microphone Cyberfinger", type: "Cyberfinger", hc: 2, cost: 100, desc: "Microphone linked to Agent or recording device. Requires Modular Finger Cyberhand." },
    { id: "bc_lighter_cyberfinger", name: "Lighter Cyberfinger", type: "Cyberfinger", hc: 3, cost: 100, desc: "Lighter concealed in the tip. Requires Modular Finger Cyberhand." },
    { id: "bc_laser_pointer_cyberfinger", name: "Laser Pointer Cyberfinger", type: "Cyberfinger", hc: 3, cost: 100, desc: "Laser pointer. 4+ can force DV13 Resist Torture/Drugs. Requires Modular Finger Cyberhand." },
    { id: "bc_wirecutter_cyberfinger", name: "Wirecutter/Scissor Cyberfingers", type: "Cyberfinger", hc: 3, cost: 100, desc: "Retractable blades, also a Poor Quality Light Melee Weapon. Requires Modular Finger Cyberhand." },
    { id: "bc_homing_tracer_cyberfinger", name: "Homing Tracer Cyberfinger", type: "Cyberfinger", hc: 3, cost: 500, desc: "Points toward linked tracer within 1 mile. Requires Modular Finger Cyberhand." },
    { id: "bc_mini_air_cyberfinger", name: "Mini Air Supply Cyberfinger", type: "Cyberfinger", hc: 2, cost: 500, desc: "10 min air supply, 1 hr to refill. Requires Modular Finger Cyberhand." },
    { id: "bc_one_shot_cyberfinger", name: "One Shot Special Cyberfinger", type: "Cyberfinger", hc: 7, cost: 100, desc: "Single-shot Exotic Heavy Pistol concealed in finger. Requires Modular Finger Cyberhand." },
    { id: "bc_spray_paint_cyberfinger", name: "Spray Paint Cyberfinger", type: "Cyberfinger", hc: 3, cost: 100, desc: "Spray can concealed within the Cyberfinger. Requires Modular Finger Cyberhand." },
    { id: "bc_squirt_cyberfinger", name: "Squirt Cyberfinger", type: "Cyberfinger", hc: 3, cost: 100, desc: "Dispenses liquids like sanitizer or perfume. Requires Modular Finger Cyberhand." }
  ],

  gear: [
    { id: "bcp_bullet_to_slug", name: "Bullet to Slug Adapter Casings", cost: 100, wt: 0.5, cat: "Weapons" },
    { id: "bcp_junk_ammo", name: "Junk Ammunition", cost: 10, wt: 0.5, cat: "Weapons" },
    { id: "bcp_small_game_ammo", name: "Small Game Ammunition", cost: 10, wt: 0.5, cat: "Weapons" },
    { id: "bcp_piranha_smash", name: "Piranha Smash", cost: 10, wt: 0.5, cat: "Medical" },
    { id: "bcp_solo_pillow", name: "Solo of Fortune Bodypillow", cost: 100, wt: 2, cat: "Fashion" },
    { id: "bc_chipvault", name: "ChipVault by SecSystems", cost: 100, wt: 0.5, cat: "Electronics" },
    { id: "bc_drinkmaster", name: "Drink Master 3000", cost: 1000, wt: 5, cat: "Tools" },
    { id: "bc_airwell", name: "Everest AirWell 50", cost: 100, wt: 2, cat: "Survival" },
    { id: "bc_one_touch_habitat", name: "Everest One Touch Habitat", cost: 100, wt: 5, cat: "Survival" },
    { id: "bc_digital_gladiator", name: "Digital Gladiator App", cost: 20, wt: 0, cat: "Electronics" },
    { id: "bc_4tify", name: "4Tify App", cost: 100, wt: 0, cat: "Electronics" },
    { id: "bc_ncpd_db", name: "NCPD Crime Database", cost: 500, wt: 0, cat: "Electronics" },
    { id: "bc_medscan", name: "Trauma Team MedScan", cost: 20, wt: 0, cat: "Medical" },
    { id: "bc_city_db", name: "Ziggurat City Database", cost: 100, wt: 0, cat: "Electronics" },
    { id: "agent", name: "Agent (Smartphone)", cost: 100, wt: 0.5, cat: "Electronics" },
    { id: "computer", name: "Computer", cost: 500, wt: 3, cat: "Electronics" },
    { id: "radio_scanner", name: "Radio Scanner", cost: 200, wt: 2, cat: "Electronics" },
    { id: "video_camera", name: "Video Camera", cost: 200, wt: 1, cat: "Electronics" },
    { id: "tape_recorder", name: "Tape Recorder", cost: 100, wt: 0.5, cat: "Electronics" },
    { id: "flashlight", name: "Flashlight", cost: 20, wt: 1, cat: "Tools" },
    { id: "rope", name: "Rope (50ft)", cost: 50, wt: 5, cat: "Tools" },
    { id: "duct_tape", name: "Duct Tape", cost: 10, wt: 1, cat: "Tools" },
    { id: "lock_mech", name: "Lock (Mechanical)", cost: 50, wt: 1, cat: "Tools" },
    { id: "lock_elec", name: "Lock (Electronic)", cost: 150, wt: 2, cat: "Tools" },
    { id: "lockpick_set", name: "Lockpick Set", cost: 100, wt: 1, cat: "Tools" },
    { id: "tech_scanner", name: "Tech Scanner", cost: 500, wt: 2, cat: "Tools" },
    { id: "tool_set", name: "Tool Set", cost: 100, wt: 5, cat: "Tools" },
    { id: "first_aid_kit", name: "First Aid Kit", cost: 100, wt: 2, cat: "Medical" },
    { id: "trauma_kit", name: "Trauma Kit", cost: 500, wt: 5, cat: "Medical" },
    { id: "anti_dote", name: "Anti-Dote", cost: 200, wt: 0.5, cat: "Medical" },
    { id: "medscanner", name: "Medscanner", cost: 500, wt: 1, cat: "Medical" },
    { id: "tent", name: "Tent", cost: 100, wt: 5, cat: "Survival" },
    { id: "sleeping_bag", name: "Sleeping Bag", cost: 50, wt: 3, cat: "Survival" },
    { id: "grapple_gun", name: "Grapple Gun", cost: 500, wt: 3, cat: "Tools" },
    { id: "night_goggles", name: "Night Goggles", cost: 200, wt: 1, cat: "Electronics" },
    { id: "binoculars", name: "Binoculars", cost: 100, wt: 1, cat: "Electronics" },
    { id: "camera", name: "Camera", cost: 200, wt: 1, cat: "Electronics" },
    { id: "grenade_incendiary", name: "Incendiary Grenade", cost: 100, wt: 1, cat: "Weapons" },
    { id: "flare", name: "Flare", cost: 20, wt: 0.5, cat: "Tools" },
    { id: "smoke_canister", name: "Smoke Canister", cost: 50, wt: 1, cat: "Tools" },
    { id: "poison", name: "Poison (D6 dmg)", cost: 200, wt: 0.5, cat: "Tools" }
  ],

  fashion: [
    { id: "generic_rack", name: "Generic (Rack)", cost: 10, desc: "Cheap, mass-produced clothing" },
    { id: "generic_urban", name: "Generic (Urban)", cost: 50, desc: "Everyday street wear" },
    { id: "generic_flash", name: "Generic (Flash)", cost: 100, desc: "Trendy, bold clothing" },
    { id: "businesswear", name: "Businesswear", cost: 500, desc: "Professional attire" },
    { id: "leisurewear", name: "Leisurewear", cost: 200, desc: "Comfortable high-end casual" },
    { id: "bodysuit", name: "Bodysuit", cost: 300, desc: "Full body suit" },
    { id: "armor_jacket", name: "Armor Jacket", cost: 100, desc: "Jacket with light armor panels" },
    { id: "raincoat", name: "Raincoat", cost: 80, desc: "Waterproof coat" },
    { id: "night_city_leathers", name: "Night City Leathers", cost: 200, desc: "Classic leather jacket and pants" }
  ],

  lifepath: {
    backgrounds: [
      "Corporate - You grew up in the corporate world.",
      "Nomad - You lived in a Nomad pack, always moving.",
      "Street - The streets raised you from a young age.",
      "Combat Zone - You grew up in the worst part of the city.",
      "Government - Your family was part of the bureaucracy.",
      "Media - You were raised around news and entertainment.",
      "Fixer - Your family worked the black market.",
      "Gang - You were raised in a gang environment.",
      "Commune - You lived in a self-sufficient commune.",
      "Military - Your family was career military."
    ],
    motivations: [
      "Money - It's always about the eddies.",
      "Reputation - You need to be known.",
      "Revenge - Someone wronged you badly.",
      "Knowledge - You seek the truth.",
      "Power - Control is everything.",
      "Freedom - No one tells you what to do.",
      "Justice - The system needs fixing.",
      "Family - Your crew is everything.",
      "Survival - Just making it to tomorrow.",
      "Fame - They will remember your name."
    ],
    hairstyles: [
      "Mohawk", "Bald", "Long", "Pixie cut", "Dreadlocks", 
      "Braided", "Pompadour", "Shaggy", "Buzzed", "Afro"
    ],
    clothing_styles: [
      "Leathers", "Neon flash", "Military surplus", "Formal wear",
      "Street punk", "Bohemian", "Corporate chic", "Nomad practical",
      "Rocker glam", "Gothic"
    ],
    life_events: [
      "Nearly died from a bad deal.",
      "Saved someone important's life.",
      "Betrayed by someone you trusted.",
      "Found something you shouldn't have.",
      "Made a powerful enemy.",
      "Lost everything and started over.",
      "Gained a loyal friend.",
      "Learned a dark secret.",
      "Won big and lost bigger.",
      "Had your first taste of real violence."
    ]
  }
};
